spring:
  application:
    name: mcro3-eureka-server

  config:
    import: configserver:http://localhost:9025

  cloud:
    config:
      fail-fast: true
      username: mcro3-configserver
      password: mcro3-123

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false